use crate::schema::{ConfigItem, ConfigType};
use anyhow::Result;
use std::collections::HashMap;
use std::fmt::Write;

pub fn generate(items: &[ConfigItem], values: &HashMap<String, toml::Value>) -> Result<String> {
    let mut buffer = String::new();

    writeln!(buffer, "/* Generated by anaxa-config */")?;
    writeln!(buffer, "#ifndef _AUTOCONF_H_")?;
    writeln!(buffer, "#define _AUTOCONF_H_")?;
    writeln!(buffer)?;

    for item in items {
        if let Some(val) = values.get(&item.name) {
            write_item_define(&mut buffer, item, val)?;
        }
    }

    writeln!(buffer)?;
    writeln!(buffer, "#endif /* _AUTOCONF_H_ */")?;

    Ok(buffer)
}

fn write_item_define(buffer: &mut String, item: &ConfigItem, val: &toml::Value) -> Result<()> {
    let name = format!("CONFIG_{}", item.name);

    match item.config_type {
        ConfigType::Bool => {
            if let Some(b) = val.as_bool() {
                if b {
                    writeln!(buffer, "#define {} 1", name)?;
                } else {
                    writeln!(buffer, "/* {} is not set */", name)?;
                }
            }
        }
        ConfigType::Int => {
            if let Some(i) = val.as_integer() {
                writeln!(buffer, "#define {} {}", name, i)?;
            }
        }
        ConfigType::Hex => {
            if let Some(i) = val.as_integer() {
                writeln!(buffer, "#define {} 0x{:x}", name, i)?;
            }
        }
        ConfigType::String | ConfigType::Choice => {
            if let Some(s) = val.as_str() {
                writeln!(buffer, "#define {} \"{}\"", name, s)?;
            }
        }
    }
    Ok(())
}
